---
title: "Ice Data"
author: "Connor Flynn"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
```

```{r}
ice_duration_df <- read_csv(here("data", 
                              "ntl33_v7.csv"), na = c("NA", -999))

meteorological_data <- read_csv(here("data",
                                     "ntl20_v6.csv"))
```

```{r}
lake_ice <- ice_duration_df %>% 
  group_by(lakeid) %>% 
  ggplot(aes(x = lakeid, y = ice_duration)) +
  geom_point()

lake_ice
```

```{r}
annual_madison_ice_cover <- ice_duration_df %>% 
  group_by(year4) %>% 
  summarise(mean_annual_madison_ice_cover = mean(ice_duration)) 
  
  
  annual_madison_ice_cover_plot <- ggplot(data = annual_madison_ice_cover, aes(x = year4, y = mean_annual_madison_ice_cover)) +
  geom_point()
  
annual_madison_ice_cover_plot

```


This visualization demonstrates a downward trend 
of mean ice coverage in the Madison lake Area from 
1850 to 2019


```{r}
madison_mean_air_temp <- meteorological_data %>% 
  group_by(year4, month) %>% 
  summarise(mean_air_temp = mean(ave_air_temp_adjusted)) %>% 
  filter(month %in% c(12,1,2))

madison_mean_air_temp_plot <- ggplot(data = madison_mean_air_temp, 
                                     aes(x = year4, y = mean_air_temp)) +
  geom_point()


madison_mean_air_temp_plot
```


```{r}
joined_data <- left_join(annual_madison_ice_cover, madison_mean_air_temp)


ggplot(data = joined_data, aes(x = mean_air_temp, y = mean_annual_madison_ice_cover)) +
  geom_point()
```

